export default {
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
  LOAD_TVSHOWS: 'LOAD_TVSHOWS',
  LOAD_TVSHOWS_ERROR: 'LOAD_TVSHOWS_ERROR',
  LOAD_DETAIL: 'LOAD_DETAIL',
  LOAD_DETAIL_ERROR: 'LOAD_DETAIL_ERROR',
  LOAD_SIMILAR: 'LOAD_SIMILAR',
  LOAD_SIMILAR_ERROR: 'LOAD_SIMILAR_ERROR',
};
